# Generated by Django 4.1.7 on 2023-04-21 11:21

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Tank', 'Танки'), ('Healer', 'Хилы'), ('DD', 'ДД'), ('vendor', 'Торговцы'), ('GuildMaster', 'Гильдмастеры'), ('QuestGiver', 'Квестгиверы'), ('Smith', 'Кузнецы'), ('Skinner', 'Кожевники'), ('Alchemist', 'Зельевары'), ('SpellMaster', 'Мастера заклинаний')], max_length=16)),
                ('title', models.CharField(max_length=64)),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('published_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseToAnnounce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=256)),
                ('response_announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response', to='Announcement.announcement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
